FROM openvino/ubuntu22_runtime:latest

ARG DEBIAN_FRONTEND=noninteractive

USER root

RUN apt update && apt install -y portaudio19-dev python-is-python3 && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -U "pip>=24"

RUN mkdir /app
WORKDIR /app

COPY requirements/server.txt /app/
RUN pip install --no-cache-dir -r server.txt && rm server.txt

COPY whisper_live /app/whisper_live
COPY run_server.py /app
CMD ["python", "run_server.py", "--backend", "openvino"]
